# Generated by Django 4.2.1 on 2024-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='More',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=50)),
                ('aimage', models.ImageField(upload_to='')),
                ('acname', models.CharField(max_length=50)),
                ('acimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
