# Generated by Django 4.2.1 on 2024-03-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='acimage',
            field=models.ImageField(upload_to='static'),
        ),
    ]
